baseURL = "https://taiwangoldcard.com/"
title = "Taiwan Gold Card - Taiwan Foreign Talent Community"
enableRobotsTXT = true
theme = "compose"
enableGitInfo = true
publishDir = "docs"

disableKinds = ["taxonomy", "taxonomyTerm"]

#  menu items
[[menu.main]]
    name = "Do I qualify?"
    weight = 1
    url = "https://visafinder.tw/gold-card-qualification/"

[[menu.main]]
    name = "Application Process"
    weight = 2
    url = "application-faq/"


[[menu.main]]
    name = "Life in Taiwan"
    weight = 3
    url = "goldcard-holders-faq/"

[[menu.main]]
    name = "Community"
    weight = 4
    url = "community"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2

# Everything below this are Site Params

[params]
  author = "Taiwan Gold Card Community"
  enableSearch = true
  searchPlaceholder = "Search..."
  repo = "https://github.com/taiwangoldcard/website"

  description = "We are a strong community of professionals with Taiwan Gold Card visa. We happily help newcomers and support each other within the Gold Card community"
  title = "Taiwan Gold Card | Taiwan Foreign Talent Community"

  # Integrate Javascript files by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "js/myscript.js"
  customJS  = []

  time_format_blog = "Monday, January 02, 2006"
  time_format_default = "January 2, 2006"
  [params.logo]
    lightMode = "gc.svg"
    darkMode = "gc-light.svg"

  [params.source]
    name = "Apply"
    icon = "github.svg"
    url = "https://coa.immigration.gov.tw/coa-frontend/four-in-one/entry/golden-card"

[outputs]
  home = ["HTML", "AMP", "RSS"]
  page = ["HTML", "AMP"]
  section = ["HTML", "AMP", "RSS"]